import { boolean, doublePrecision, index, integer, jsonb, pgTable, text, timestamp } from 'drizzle-orm/pg-core';
import { sql } from 'drizzle-orm';

/**
 * Server-owned admin AI configuration (assistants & PBL teams).
 *
 * These tables back the admin console 「助手 / 团队」 tables. Client-writable
 * fields are whitelisted in `services/api/.../admin-ai-config.validation.ts`;
 * everything marked *server-owned* below is derived by the API and can never be
 * supplied by a request body:
 * - `admin_assistants.source` / `agent_status` / `agent_status_message`
 * - `deletable` is derived from `source` (`builtin` assistants are never deletable).
 * - `admin_team_members.assistant_name` / `avatar` / `status` are resolved from
 *   the referenced assistant row at read time; `status` is server-owned runtime state.
 * - `pbl_spec` is normalized by the server: `theoryMasteredGate` is hard-coded
 *   `true`, `concept_mastery` phases always carry the `TheoryMastered` gate.
 */
export const adminAssistants = pgTable(
  'admin_assistants',
  {
    id: text('id').primaryKey(),
    /** Server-owned: 'builtin' | 'generated' | 'user'. */
    source: text('source').notNull().default('user'),
    name: text('name').notNull(),
    avatar: text('avatar'),
    description: text('description').notNull().default(''),
    role: text('role').notNull().default(''),
    enabled: boolean('enabled').notNull().default(true),
    sortOrder: integer('sort_order').notNull().default(0),
    modelProviderId: text('model_provider_id'),
    modelId: text('model_id'),
    temperature: doublePrecision('temperature'),
    instructions: text('instructions').notNull().default(''),
    enabledSkills: jsonb('enabled_skills').$type<string[]>().notNull().default(sql`'[]'::jsonb`),
    toolIds: jsonb('tool_ids').$type<string[]>().notNull().default(sql`'[]'::jsonb`),
    mcpServerIds: jsonb('mcp_server_ids').$type<string[]>().notNull().default(sql`'[]'::jsonb`),
    /** Server-owned snapshot of `AssistantDefaults` (partial overrides merged server-side). */
    defaults: jsonb('defaults').$type<Record<string, unknown>>().notNull().default(sql`'{}'::jsonb`),
    /** Server-owned runtime probe state: 'missing' | 'online' | 'offline' | 'unchecked'. */
    agentStatus: text('agent_status').notNull().default('unchecked'),
    agentStatusMessage: text('agent_status_message'),
    teamSelectable: boolean('team_selectable').notNull().default(true),
    updatedBy: text('updated_by'),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => ({
    enabledSortIdx: index('admin_assistants_enabled_sort_idx').on(table.enabled, table.sortOrder),
    selectableIdx: index('admin_assistants_selectable_idx').on(table.teamSelectable, table.enabled),
  }),
);

/**
 * Collaborative PBL teams. `pbl_spec` stores the *normalized* server copy of
 * `PblTeamWorkflowSpec`; the TheoryMastered hard gate lives inside it and is
 * never written verbatim from a client payload.
 */
export const adminTeams = pgTable(
  'admin_teams',
  {
    id: text('id').primaryKey(),
    name: text('name').notNull(),
    description: text('description').notNull().default(''),
    /** 'shared' | 'isolated' (validated server-side). */
    workspaceMode: text('workspace_mode').notNull().default('shared'),
    /** 'auto' | 'plan' | 'supervised' (validated server-side). */
    sessionMode: text('session_mode').notNull().default('supervised'),
    leaderAssistantId: text('leader_assistant_id')
      .notNull()
      .references(() => adminAssistants.id, { onDelete: 'restrict' }),
    concurrencyLimit: integer('concurrency_limit').notNull().default(1),
    pblSpec: jsonb('pbl_spec').$type<Record<string, unknown> | null>(),
    enabled: boolean('enabled').notNull().default(true),
    updatedBy: text('updated_by'),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => ({
    leaderIdx: index('admin_teams_leader_idx').on(table.leaderAssistantId),
    enabledIdx: index('admin_teams_enabled_idx').on(table.enabled),
  }),
);

/**
 * Assistant assignments inside a team. `slot_id` is generated by the server when
 * absent and stays stable across PATCH replays that carry it back.
 * `status` is a server-owned runtime projection (never client-writable).
 */
export const adminTeamMembers = pgTable(
  'admin_team_members',
  {
    slotId: text('slot_id').primaryKey(),
    teamId: text('team_id')
      .notNull()
      .references(() => adminTeams.id, { onDelete: 'cascade' }),
    assistantId: text('assistant_id')
      .notNull()
      .references(() => adminAssistants.id, { onDelete: 'restrict' }),
    /** 'leader' | 'teammate' | 'reviewer' | 'coach' (validated server-side). */
    role: text('role').notNull(),
    roleLabel: text('role_label'),
    model: text('model'),
    color: text('color'),
    /** Optional PBL phase anchor for this member. */
    pblPhase: text('pbl_phase'),
    /** Server-owned runtime status: 'pending' | 'idle' | 'active' | 'completed' | 'failed' | 'dormant'. */
    status: text('status').notNull().default('idle'),
    sortOrder: integer('sort_order').notNull().default(0),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => ({
    teamSortIdx: index('admin_team_members_team_sort_idx').on(table.teamId, table.sortOrder),
    assistantIdx: index('admin_team_members_assistant_idx').on(table.assistantId),
  }),
);
